#ifndef BLOCKS_H
#define BLOCKS_H

/**
 * This file includes every Block
 */

#include "conditional/ifblock.h"
#include "conditional/ifelseblock.h"
#include "conditional/waituntilblock.h"
#include "conditional/waitsecondsblock.h"
#include "event/mouseclickblock.h"
#include "event/startblock.h"
#include "event/arrowupblock.h"
#include "event/arrowdownblock.h"
#include "event/arrowleftblock.h"
#include "event/arrowrightblock.h"
#include "event/enterblock.h"
#include "event/spaceblock.h"
#include "event/messagesignalreceivedblock.h"
#include "event/sendmessagesignaltospriteblock.h"
#include "loop/whileblock.h"
#include "loop/repeatxblock.h"
#include "number/numberassignment.h"
#include "number/plusblock.h"
#include "number/minusblock.h"
#include "number/multiplyblock.h"
#include "number/divideblock.h"
#include "number/randomblock.h"
#include "number/equalnumberblock.h"
#include "number/lessthannumberblock.h"
#include "number/greaterthannumberblock.h"
#include "sprite/nextimageblock.h"
#include "sprite/rotatespriteblock.h"
#include "sprite/gotopositionblock.h"
#include "sprite/gotospriteblock.h"
#include "sprite/movestepsblock.h"
#include "sprite/collidesspriteblock.h"
#include "sprite/bounceedgeblock.h"
#include "sprite/setvisibleblock.h"
#include "sprite/setinvisibleblock.h"
#include "sprite/resizeblock.h"
#include "sprite/resizetoblock.h"
#include "sprite/spriteheightblock.h"
#include "sprite/spritewidthblock.h"
#include "sprite/spritexposblock.h"
#include "sprite/spriteyposblock.h"
#include "sprite/spriterotationblock.h"
#include "sprite/spritevisibleblock.h"
#include "bool/boolassignmentblock.h"
#include "bool/logicalandblock.h"
#include "bool/logicalorblock.h"
#include "bool/logicalnotblock.h"
#include "bool/equalboolblock.h"
#include "string/concatenateblock.h"
#include "string/charatblock.h"
#include "string/lengthblock.h"
#include "string/equalstringblock.h"
#include "string/convertnumbertostringblock.h"
#include "string/stringassignmentblock.h"
#include "io/printblock.h"
#include "io/askblock.h"
#include "list/numberfromlistblock.h"
#include "list/addnumbertolistblock.h"
#include "list/appendnumbertolist.h"
#include "list/numberlistsize.h"

#endif // BLOCKS_H
